packages:
  - workflow
  - model
  - ui
  - test
  - block

catalog:
  "@platforma-sdk/model": ^1.42.36
  "@platforma-sdk/ui-vue": ^1.42.44
  "@platforma-sdk/workflow-tengo": ^5.1.1
  "@platforma-sdk/block-tools": ^2.5.92
  "@platforma-sdk/test": ^1.42.44
  "@platforma-sdk/tengo-builder": ^2.1.17
  "@platforma-sdk/package-builder": ^3.2.3
  "@platforma-sdk/eslint-config": ^1.0.3
  "@platforma-sdk/blocks-deps-updater": ^2.0.0

  "@platforma-open/milaboratories.runenv-python-3": ^1.3.1
  
  "vue": ^3.5.15
  "vue-tsc": ^2.2.10
  
  "typescript": ~5.5.4
  "turbo": ^2.5.4

  "vite": ^6.3.5
  "vitest": ~2.1.9
  "@vitejs/plugin-vue": ^5.2.4
  "vite-plugin-dts": ^4.3.0

  "@changesets/cli": ^2.29.5
